services:
  api-gateway-tester:
    container_name: api-gateway-tester
    build:
      context: ./api-gateway
    environment:
      NODE_ENV: test
    env_file:
      - ./api-gateway/config/.env.test
    command: npm run test
    networks:
      - test-network

  article-service-tester:
    container_name: article-service-tester
    build:
      context: ./articles-service
    environment:
      NODE_ENV: test
    env_file:
      - ./articles-service/config/.env.test
    command: npm run test
    networks:
      - test-network


networks:
  test-network:
    driver: bridge


#  log-service:
#    command: ["./wait-for.sh", "log-service", "3002", "npm", "run", "test"]
#
#  search-service:
#    command: ["./wait-for.sh", "search-service", "3003", "npm", "run", "test"]
