services:
  api-gateway:
    container_name: api-gateway-service_articles-platform_test
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - '${HOST_PORT_API_GATEWAY}:${CONTAINER_PORT_API_GATEWAY}'
    env_file:
      - ./api-gateway/config/.env.test
    environment:
      NODE_ENV: test
    command: npm run start:dev
    restart: on-failure
