services:
  article-service-db:
    container_name: article-service-database_articles-platform
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - article_db_data:/var/lib/postgresql/data
    env_file:
      - ./articles-service/config/.env.dev
    restart: unless-stopped


  log-service-db:
    container_name: log-service-database_articles-platform
    image: postgres
    ports:
      - '5433:5432'
    volumes:
      - log_db_data:/var/lib/postgresql/data
    env_file:
      - ./log-service/config/.env.dev
    restart: unless-stopped

volumes:
  article_db_data:
  log_db_data:
