services:
  postgres-test:
    image: postgres:15
    container_name: article-service-test-database_articles-platform
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: articles-platform-test-db
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata_test:/var/lib/postgresql/data
