services:
  api-gateway-tester:
    container_name: api-gateway-tester
    build:
      context: ./api-gateway
    volumes:
      - ./wait-for.sh:/wait-for.sh  # Монтируем в корень
    command: npm run test
    networks:
      - test-network



networks:
  test-network:
    driver: bridge

#  article-service:
#    command: ["./wait-for.sh", "article-service", "3001", "npm", "run", "test"]
#
#  log-service:
#    command: ["./wait-for.sh", "log-service", "3002", "npm", "run", "test"]
#
#  search-service:
#    command: ["./wait-for.sh", "search-service", "3003", "npm", "run", "test"]
