global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alert-manager:9093' ]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'elasticsearch-exporter'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']

  - job_name: "article-postgres"
    static_configs:
      - targets: ["article-postgres-exporter:9187"]

  - job_name: "log-postgres"
    static_configs:
      - targets: ["log-postgres-exporter:9187"]

  - job_name: "api-gateway"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api-gateway:3000"]

  - job_name: "article-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["article-service:3001"]
