groups:
  - name: node_alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Instance [{{ $labels.instance }}] down"
          description: "[{{ $labels.instance }}] of job {{ $labels.job }} has been down for more than 30 seconds."

#  - name: node_alerts
#    rules:
      - alert: HighCpuUsage
        expr: rate(node_cpu_seconds_total{mode!="idle"}[1m]) > 0.9
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Высокая загрузка CPU на {{ $labels.instance }}"
          description: "CPU загружен более чем на 90% более 2 минут"

      - alert: HostMemoryIsUnderutilized
        expr: ({__name__="node_memory_MemAvailable_bytes", instance="node-exporter:9100", job="node"} > 80)
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: Host Memory is underutilized (instance {{ $labels.instance }})
          description: "Node memory is < 20% for 1 week. Consider reducing memory space. (instance {{ $labels.instance }})\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"